In [1]:
#import the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r"C:\Users\cse\Desktop\AI\forestfires.csv")

In [3]:
df

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
5    8  6   aug  sun  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.00
6    8  6   aug  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.00
7    8  6   aug  mon  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.00
8    8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.00
9    7  5   sep  sat  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.00
10   7  5   sep  sat  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0   0.00
11   7  5   sep  sat  92.8   73.2  713.0  22.6  19.3  38   4.0   0.0   0.00
12   6  5   aug  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.00
13   6  5   sep  mon  90.9  126.5  686.5   7.0  21.3  42   2.2   0.0   0.00
14   6  5   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0   0.00
15   6  5   sep  fri  93.3  141.2  713.9  13.9  22.9  44   5.4   0.0   0.00
16   5  5   mar  sat  91.7   35.8   80.8   7.8  15.1  27   5.4   0.0   0.00
17   8  5   oct  mon  84.9   32.8  664.2   3.0  16.7  47   4.9   0.0   0.00
18   6  4   mar  wed  89.2   27.9   70.8   6.3  15.9  35   4.0   0.0   0.00
19   6  4   apr  sat  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0   0.00
20   6  4   sep  tue  91.0  129.5  692.6   7.0  18.3  40   2.7   0.0   0.00
21   5  4   sep  mon  91.8   78.5  724.3   9.2  19.1  38   2.7   0.0   0.00
22   7  4   jun  sun  94.3   96.3  200.0  56.1  21.0  44   4.5   0.0   0.00
23   7  4   aug  sat  90.2  110.9  537.4   6.2  19.5  43   5.8   0.0   0.00
24   7  4   aug  sat  93.5  139.4  594.2  20.3  23.7  32   5.8   0.0   0.00
25   7  4   aug  sun  91.4  142.4  601.4  10.6  16.3  60   5.4   0.0   0.00
26   7  4   sep  fri  92.4  117.9  668.0  12.2  19.0  34   5.8   0.0   0.00
27   7  4   sep  mon  90.9  126.5  686.5   7.0  19.4  48   1.3   0.0   0.00
28   6  3   sep  sat  93.4  145.4  721.4   8.1  30.2  24   2.7   0.0   0.00
29   6  3   sep  sun  93.5  149.3  728.6   8.1  22.8  39   3.6   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
487  5  4   aug  tue  95.1  141.3  605.8  17.7  26.4  34   3.6   0.0  16.40
488  4  4   aug  tue  95.1  141.3  605.8  17.7  19.4  71   7.6   0.0  46.70
489  4  4   aug  wed  95.1  141.3  605.8  17.7  20.6  58   1.3   0.0   0.00
490  4  4   aug  wed  95.1  141.3  605.8  17.7  28.7  33   4.0   0.0   0.00
491  4  4   aug  thu  95.8  152.0  624.1  13.8  32.4  21   4.5   0.0   0.00
492  1  3   aug  fri  95.9  158.0  633.6  11.3  32.4  27   2.2   0.0   0.00
493  1  3   aug  fri  95.9  158.0  633.6  11.3  27.5  29   4.5   0.0  43.32
494  6  6   aug  sat  96.0  164.0  643.0  14.0  30.8  30   4.9   0.0   8.59
495  6  6   aug  mon  96.2  175.5  661.8  16.8  23.9  42   2.2   0.0   0.00
496  4  5   aug  mon  96.2  175.5  661.8  16.8  32.6  26   3.1   0.0   2.77
497  3  4   aug  tue  96.1  181.1  671.2  14.3  32.3  27   2.2   0.0  14.68
498  6  5   aug  tue  96.1  181.1  671.2  14.3  33.3  26   2.7   0.0  40.54
499  7  5   aug  tue  96.1  181.1  671.2  14.3  27.3  63   4.9   6.4  10.82
500  8  6   aug  tue  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
501  7  5   aug  tue  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
502  4  4   aug  tue  96.1  181.1  671.2  14.3  20.7  69   4.9   0.4   0.00
503  2  4   aug  wed  94.5  139.4  689.1  20.0  29.2  30   4.9   0.0   1.95
504  4  3   aug  wed  94.5  139.4  689.1  20.0  28.9  29   4.9   0.0  49.59
505  1  2   aug  thu  91.0  163.2  744.4  10.1  26.7  35   1.8   0.0   5.80
506  1  2   aug  fri  91.0  166.9  752.6   7.1  18.5  73   8.5   0.0   0.00
507  2  4   aug  fri  91.0  166.9  752.6   7.1  25.9 

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df.isnull().any()

X        False
Y        False
month    False
day      False
FFMC     False
DMC      False
DC       False
ISI      False
temp     False
RH       False
wind     False
rain     False
area     False
dtype: bool

In [6]:
type(df)

pandas.core.frame.DataFrame

In [7]:
df.drop(["month"],axis=1,inplace=True)

In [8]:
df.drop(["day"],axis=1,inplace=True)

In [9]:
df

X  Y  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
5    8  6  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.00
6    8  6  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.00
7    8  6  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.00
8    8  6  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.00
9    7  5  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.00
10   7  5  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0   0.00
11   7  5  92.8   73.2  713.0  22.6  19.3  38   4.0   0.0   0.00
12   6  5  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.00
13   6  5  90.9  126.5  686.5   7.0  21.3  42   2.2   0.0   0.00
14   6  5  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0   0.00
15   6  5  93.3  141.2  713.9  13.9  22.9  44   5.4   0.0   0.00
16   5  5  91.7   35.8   80.8   7.8  15.1  27   5.4   0.0   0.00
17   8  5  84.9   32.8  664.2   3.0  16.7  47   4.9   0.0   0.00
18   6  4  89.2   27.9   70.8   6.3  15.9  35   4.0   0.0   0.00
19   6  4  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0   0.00
20   6  4  91.0  129.5  692.6   7.0  18.3  40   2.7   0.0   0.00
21   5  4  91.8   78.5  724.3   9.2  19.1  38   2.7   0.0   0.00
22   7  4  94.3   96.3  200.0  56.1  21.0  44   4.5   0.0   0.00
23   7  4  90.2  110.9  537.4   6.2  19.5  43   5.8   0.0   0.00
24   7  4  93.5  139.4  594.2  20.3  23.7  32   5.8   0.0   0.00
25   7  4  91.4  142.4  601.4  10.6  16.3  60   5.4   0.0   0.00
26   7  4  92.4  117.9  668.0  12.2  19.0  34   5.8   0.0   0.00
27   7  4  90.9  126.5  686.5   7.0  19.4  48   1.3   0.0   0.00
28   6  3  93.4  145.4  721.4   8.1  30.2  24   2.7   0.0   0.00
29   6  3  93.5  149.3  728.6   8.1  22.8  39   3.6   0.0   0.00
..  .. ..   ...    ...    ...   ...   ...  ..   ...   ...    ...
487  5  4  95.1  141.3  605.8  17.7  26.4  34   3.6   0.0  16.40
488  4  4  95.1  141.3  605.8  17.7  19.4  71   7.6   0.0  46.70
489  4  4  95.1  141.3  605.8  17.7  20.6  58   1.3   0.0   0.00
490  4  4  95.1  141.3  605.8  17.7  28.7  33   4.0   0.0   0.00
491  4  4  95.8  152.0  624.1  13.8  32.4  21   4.5   0.0   0.00
492  1  3  95.9  158.0  633.6  11.3  32.4  27   2.2   0.0   0.00
493  1  3  95.9  158.0  633.6  11.3  27.5  29   4.5   0.0  43.32
494  6  6  96.0  164.0  643.0  14.0  30.8  30   4.9   0.0   8.59
495  6  6  96.2  175.5  661.8  16.8  23.9  42   2.2   0.0   0.00
496  4  5  96.2  175.5  661.8  16.8  32.6  26   3.1   0.0   2.77
497  3  4  96.1  181.1  671.2  14.3  32.3  27   2.2   0.0  14.68
498  6  5  96.1  181.1  671.2  14.3  33.3  26   2.7   0.0  40.54
499  7  5  96.1  181.1  671.2  14.3  27.3  63   4.9   6.4  10.82
500  8  6  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
501  7  5  96.1  181.1  671.2  14.3  21.6  65   4.9   0.8   0.00
502  4  4  96.1  181.1  671.2  14.3  20.7  69   4.9   0.4   0.00
503  2  4  94.5  139.4  689.1  20.0  29.2  30   4.9   0.0   1.95
504  4  3  94.5  139.4  689.1  20.0  28.9  29   4.9   0.0  49.59
505  1  2  91.0  163.2  744.4  10.1  26.7  35   1.8   0.0   5.80
506  1  2  91.0  166.9  752.6   7.1  18.5  73   8.5   0.0   0.00
507  2  4  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
508  1  2  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
509  5  4  91.0  166.9  752.6   7.1  21.1  71   7.6   1.4   2.17
510  6  5  91.0  166.9  752.6   7.1  18.2  62   5.4   0.0   0.43
511  8  6  81.6   56.7  665.6   1.9  27.8  35   2.7   0.0   0.00
512  4  3  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3  79.5    3.0  106.7   1.1  11.

In [10]:
X = df.iloc[:, :-1].values
y = df.iloc[:, 10].values

In [11]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X, y)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [12]:
y_pred=regressor.predict([[7,5,86.2,26.2,94.3,5.1,8.2,51,6.7,0]])

In [13]:
y_pred

array([5.049])

In [14]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [18]:
X_train

array([[ 6. ,  3. , 91.6, ..., 34. ,  2.2,  0. ],
       [ 8. ,  6. , 92.5, ..., 56. ,  1.8,  0. ],
       [ 7. ,  4. , 90.1, ..., 57. ,  4.5,  0. ],
       ...,
       [ 3. ,  4. , 91. , ..., 59. ,  6.3,  0. ],
       [ 5. ,  5. , 91.7, ..., 27. ,  5.4,  0. ],
       [ 6. ,  3. , 84.1, ..., 42. ,  2.7,  0. ]])

In [19]:
X_test

array([[ 8. ,  6. , 88.8, ..., 66. ,  5.4,  0. ],
       [ 6. ,  4. , 90.4, ..., 46. ,  1.8,  0. ],
       [ 2. ,  5. , 91. , ..., 46. ,  3.1,  0. ],
       ...,
       [ 2. ,  4. , 95.2, ..., 19. ,  4.5,  0. ],
       [ 4. ,  3. , 90.3, ..., 44. ,  3.1,  0. ],
       [ 1. ,  3. , 95.9, ..., 29. ,  4.5,  0. ]])

In [20]:
y_train

array([5.6040e+01, 1.9500e+00, 3.7710e+01, 5.4000e-01, 8.2750e+01,
       1.6900e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       2.4400e+00, 1.0010e+01, 0.0000e+00, 5.5000e-01, 1.0930e+01,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 4.9590e+01, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 3.2070e+01, 0.0000e+00, 0.0000e+00,
       3.7800e+00, 1.3700e+01, 0.0000e+00, 7.9000e-01, 0.0000e+00,
       2.7400e+00, 2.4000e-01, 1.0730e+01, 0.0000e+00, 6.1130e+01,
       0.0000e+00, 5.2000e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       7.0760e+01, 1.0080e+01, 6.8300e+00, 0.0000e+00, 2.1400e+00,
       0.0000e+00, 1.4680e+01, 2.8660e+01, 4.8800e+00, 3.6400e+00,
       0.0000e+00, 6.5800e+00, 2.5700e+00, 1.5800e+00, 0.0000e+00,
       4.6700e+01, 2.4240e+01, 0.0000e+00, 7.7000e-01, 0.0000e+00,
       7.2000e-01, 0.0000e+00, 2.9480e+01, 2.1000e-01, 0.0000e+00,
       3.7020e+01, 1.8300e+01, 0.0000e+00, 3.2000e+00, 1.7600e+00,
       2.0300e+00, 0.0000e+00, 2.4590e+01, 0.0000e+00, 1.0339e

In [21]:
y_test

array([5.23000e+00, 9.00000e-01, 7.04000e+00, 2.55000e+00, 0.00000e+00,
       5.38000e+00, 0.00000e+00, 1.74630e+02, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 8.64500e+01, 0.00000e+00, 0.00000e+00, 7.46280e+02,
       0.00000e+00, 2.51000e+00, 8.24000e+00, 0.00000e+00, 0.00000e+00,
       7.48000e+00, 1.10600e+01, 6.96000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 5.33000e+00, 6.84000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 3.35000e+00, 0.00000e+00,
       4.10000e-01, 1.72000e+01, 0.00000e+00, 2.14000e+00, 0.00000e+00,
       8.71000e+00, 0.00000e+00, 0.00000e+00, 2.78530e+02, 0.00000e+00,
       0.00000e+00, 7.36000e+00, 1.01000e+00, 6.43000e+00, 2.18000e+00,
       1.75000e+00, 4.41000e+00, 2.69000e+00, 0.00000e+00, 1.13200e+01,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 3.71000e+00, 5.86000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 1.46000e+00,
       7.03200e+01, 4.93700e+01, 0.00000e+00, 0.00000e+00, 0.000

In [22]:
X_train.shape

(413, 10)

In [27]:
y_pred=regressor.predict(X_test)

In [28]:
y_pred

array([3.13800000e+00, 3.05400000e+00, 3.44400000e+01, 3.13400000e+00,
       1.42900000e+00, 5.38700000e+00, 2.25950000e+01, 1.05098000e+02,
       2.61300000e+00, 1.55400000e+00, 0.00000000e+00, 4.45800000e+01,
       6.78800000e+00, 0.00000000e+00, 6.72511000e+02, 7.69600000e+00,
       4.71000000e+00, 1.04530000e+01, 8.76000000e-01, 3.85300000e+00,
       1.71920000e+01, 2.10180000e+01, 5.56800000e+00, 5.73200000e+00,
       8.62200000e+00, 0.00000000e+00, 3.19800000e+00, 6.01000000e+00,
       1.47000000e-01, 2.21000000e-01, 0.00000000e+00, 1.64200000e+00,
       9.96000000e-01, 2.88500000e+00, 4.68000000e-01, 4.05800000e+00,
       1.07970000e+01, 2.46600000e+00, 2.57600000e+00, 0.00000000e+00,
       8.55766667e+00, 2.75000000e-01, 2.29600000e+00, 2.50677000e+02,
       2.14000000e-01, 4.42000000e-01, 2.54130000e+01, 2.53100000e+01,
       6.73200000e+00, 1.50200000e+00, 3.22000000e+00, 1.81170000e+01,
       5.85000000e+00, 5.10900000e+00, 1.15580000e+01, 0.00000000e+00,
      

In [30]:
from sklearn.metrics import r2_score

In [31]:
r2_score(y_test,y_pred)

0.8762747796746785